### ISSUE TITLE
$http.get(...).success is not a function

### ISSUE THREAD

**Issue by Acraciel** [dmunozgaete/Angular-Gale#7]
![error - captura realizada el 2016-12-09 15 22 36](https://cloud.githubusercontent.com/assets/8073692/21059951/d031c212-be23-11e6-8423-3ee3b18d98c8.png)

![error- captura realizada el 2016-12-09 15 21 58](https://cloud.githubusercontent.com/assets/8073692/21059954/d7a803c6-be23-11e6-8f87-ff980d2c542a.png)

Solo actualicé, ya que llamo siempre a la ultima versión de la rama Master y me dio este problema.

Saludos.

**Comment by Acraciel** [comment]
Por lo que estuve viendo quizás alguna dependencia hizo una actualización que afecto a esta funcionalidad... ya que pude rescatar los componentes del bower y los node_component y funcionó bien como siempre.

**Comment by dmunozgaete** [comment]
Rodrigo!, gracias!, efectivamente , es una actualización del angular , específicamente desde la versión 1..5.9 en adelante cambiaron la forma de inicialización y métodos del modulo "$http", por lo que la forma de ejecución actual , no está funcionando. 

Como solución temporal(workaround):
en el bower.json "fija" la versión del angular a <=1.4.8 por ejemplo , para que no actualice angular a su versión 1.6.0 que es la actual y que contiene el cambio.

``
#bower.json
"dependencies": {
 "angular": "1.4.8"
 },
 "resolutions": {
    "angular-gale": "master"
  },
``

La solución correcta , implica subir a una version "major" de angular-gale con soporte a angular mayor a 1.4.8 por lo que actualmente está en desarrollo. 

cualquier actualización del milestone y roadmap , aparecerán por aca.

Saludos!

**Comment by dmunozgaete** [comment]
Aca esta un ejemplo del workaround para que bower fije la versión de angular:


<img width="1247" alt="captura de pantalla 2016-12-15 a las 11 04 58" src="https://cloud.githubusercontent.com/assets/5934807/21226897/6281f344-c2b6-11e6-9265-139ff3ac95d5.png">

Saludos!
